name: CICD

on: [push]

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Lancer php-cs-fixer
        run: composer cs-fixer
      - name: Lancer php-stan
        run: composer stan
      - uses: php-actions/phpunit@v3